{
    "openapi" : "3.0.3",
    "info": {
        "title": "Todolist RESTful API",
        "version": "1",
        "description": "OpenAPI for Todolist RESTful API",
        "termsOfService": "https://github.com/FruHafizd",
        "contact": {
            "name": "Muhammad Hafizd",
            "email": "muhammadhafizd876@gmail.com",
            "url": "https://github.com/FruHafizd"
        },
        "license": {
            "name": "APACHE 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0"
        }
    },

    "servers": [
        {
            "description": "Todolist RESTful API Server",
            "url": "https://{environment}.github.com/FruHafizd/api/v1",
            "variables": {
                "environment" : {
                    "description": "Server Environment",
                    "default": "dev",
                    "enum": [
                        "dev",
                        "qa",
                        "prod"
                    ]
                }
            }
        }
    ],

    "externalDocs": {
        "description": "FruHafizd Belajar Restful OpenAPI Specs",
        "url": "https://github.com/FruHafizd"
    },

    "paths": {
        "/todolist" : {
            "get" : {
                "security": [
                    {
                        "TodolistAuth" : []
                    }
                ],
                "tags": ["Todolist"],
                "summary": "Get All Todolist",
                "description": "Get all active todolist by deafult",
                "parameters": [
                    {
                        "name": "include_done",
                        "in": "query",
                        "required": false,
                        "description": "Is include done todolist",
                        "schema" : {
                            "type": "boolean",
                            "nullable": true,
                            "default" : false
                        }
                    },
                    {
                        "name": "name",
                        "in": "query",
                        "required": false,
                        "description": "Filter todolist by name",
                        "schema" : {
                            "type": "string",
                            "nullable": true,
                            "minLength": 1,
                            "maxLength": 100
                        },
                        "examples" : {
                            "java" : {
                                "description": "Exampe Name Java",
                                "value" : "Java"
                            },
                            "php" : {
                                "description": "Example name PHP",
                                "value" : "PHP"
                            }
                        }
                    }
                ],
                "responses": {
                    "200" : {
                        "description": "Succes get all todolist",
                        "content": {
                            "application/json" : {
                                "schema" : {
                                    "$ref"  : "#/components/schemas/ArrayTodolist"
                                },
                                "examples": {
                                    "success" : {
                                        "description": "Example success get all toodlist",
                                        "value": [
                                            {
                                                "id" : "1",
                                                "name": "Java",
                                                "priority": 3,
                                                "tags": [
                                                    "Java",
                                                    "Programming"
                                                ]
                                            },
                                            {
                                                "id" : "2",
                                                "name": "PHP",
                                                "priority": 5,
                                                "tags": [
                                                    "PHP",
                                                    "Programming"
                                                ]
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post" : {
                "security": [
                    {
                        "TodolistAuth" : []
                    }
                ],
                "tags": ["Todolist"],
                "summary": "Create new todolist",
                "description": "Create new todolist to database",
                "requestBody" : {
                    "required": true,
                    "content": {
                        "application/json" : {
                            "schema": {
                                "$ref" : "#/components/schemas/CreateOrUpdateTodolist"
                            },
                            "examples" : {
                                "java" : {
                                    "description" : "Example create todolist Java" ,
                                    "value" : {
                                        "name" : "Java",
                                        "priority" : 3,
                                        "tags" : [
                                            "Java",
                                            "Programming"
                                        ]
                                    }
                                },

                                "php" : {
                                    "description" : "Example create todolist PHP" ,
                                    "value" : {
                                        "name" : "PHP",
                                        "priority" : 5,
                                        "tags" : [
                                            "PHP",
                                            "Programming"
                                        ]
                                    }
                                }
                                
                            }
                        }
                    }
                },
                "responses": {
                    "200" : {
                        "description": "Success Create todolist",
                        "content": {
                            "application/json" : {
                                "schema" : {
                                    "$ref"  : "#/components/schemas/Todolist"
                                },
                                "examples": {
                                    "java" : {
                                        "description": "Success create java todolist",
                                        "value" : {
                                            "id" : "1",
                                            "name" : "Java",
                                            "priority" : 3,
                                            "tags" : [
                                                "Java",
                                                "Programming"
                                            ]
                                        }
                                    },
                                    "php" : {
                                        "description": "Success create php todolist",
                                        "value" : {
                                            "id" : "2",
                                            "name" : "PHP",
                                            "priority" : 5,
                                            "tags" : [
                                                "PHP",
                                                "Programming"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },

        "/todolist/{todolistId}" : {
            "put" : {
                "security": [
                    {
                        "TodolistAuth" : []
                    }
                ],
                "tags": ["Todolist"],
                "summary": "Update existing todolist",
                "description": "Update existing todolist in database",
                "parameters": [
                    {
                        "$ref" : "#/components/parameters/todolistId"
                    }
                ],
                "requestBody" : {
                    "required": true,
                    "content": {
                        "application/json" : {
                            "schema": {
                                "$ref" : "#/components/schemas/Todolist"
                            },
                            "examples" : {
                                "java" : {
                                    "description" : "Example create todolist Java" ,
                                    "value" : {
                                        "name" : "Java",
                                        "priority" : 3,
                                        "tags" : [
                                            "Java",
                                            "Programming"
                                        ]
                                    }
                                },

                                "php" : {
                                    "description" : "Example create todolist PHP" ,
                                    "value" : {
                                        "name" : "PHP",
                                        "priority" : 5,
                                        "tags" : [
                                            "PHP",
                                            "Programming"
                                        ]
                                    }
                                }
                                
                            }
                        }
                    }
                },
                
                "responses": {
                    "200" : {
                        "description": "Success Update todolist",
                        "content": {
                            "application/json" : {
                                "schema" : {
                                    "$ref": "#/components/schemas/Todolist"
                                },
                                "examples": {
                                    "java" : {
                                        "description": "Success create java todolist",
                                        "value" : {
                                            "id" : "1",
                                            "name" : "Java",
                                            "priority" : 3,
                                            "tags" : [
                                                "Java",
                                                "Programming"
                                            ]
                                        }
                                    },
                                    "php" : {
                                        "description": "Success create php todolist",
                                        "value" : {
                                            "id" : "2",
                                            "name" : "PHP",
                                            "priority" : 5,
                                            "tags" : [
                                                "PHP",
                                                "Programming"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete" : {
                "security": [
                    {
                        "TodolistAuth" : []
                    }
                ],
                "tags": ["Todolist"],
                "summary": "Delete existing todolist",
                "description": "Delete existing todolist in database",
                "parameters": [
                    {
                        "$ref" : "#/components/parameters/todolistId"
                    }
                ],
                "responses": {
                    "200" : {
                        "description": "Succes delete todolist",
                        "content": {
                            "application/json" : {
                                "schema" : {
                                    "type": "object",
                                    "properties": {
                                        "success" : {
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples" : {
                                    "success" : {
                                        "description" : "Success delete todolist",
                                        "value" : {
                                            "success" : true
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404" : {
                        "description": "Failed delete not found todolist",
                        "content": {
                            "application/json" : {
                                "schema" : {
                                    "type": "object",
                                    "properties": {
                                        "success" : {
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples" : {
                                    "failed" : {
                                        "description" : "Failed delete todolist",
                                        "value" : {
                                            "success" : false
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },

    "components": {
        "securitySchemes": {
            "TodolistAuth" : {
                "description": "Authentication For Todolist RestFul API",
                "type": "apiKey",
                "in": "header",
                "name": "X-API-KEY"
            }
        },

        "parameters": {
            "todolistId" : 
            {
                "name": "todolistId",
                "in": "path",
                "required": true,
                "description": "Todolist id for Updated",
                "schema" : {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 100
                },
                "examples" : {
                    "java" : {
                        "description": "Sample todolist id for Java",
                        "value" : "1"
                    },
                    "php" : {
                        "description": "Sample todolist id for PHP",
                        "value" : "2"
                    }

                }
            }
        },
        "schemas": {
            "Todolist" : {
                "type": "object",
                "properties": {
                    "id" : {
                        "type": "string"
                    },
                    "name" : {
                        "type": "string"
                    },
                    "priority" : {
                        "type": "number",
                        "format": "int32"
                    },
                    "tags" : {
                        "type": "array",
                        "items" : {
                            "type": "string"
                        }
                    }
                }
            },
            "CreateOrUpdateTodolist" : {
                "type": "object",
                "properties": {
                    "id" : {
                        "type": "string"
                    },
                    "name" : {
                        "type": "string"
                    },
                    "priority" : {
                        "type": "number",
                        "format": "int32"
                    },
                    "tags" : {
                        "type": "array",
                        "items" : {
                            "type": "string"
                        }
                    }
                }
            },
            "ArrayTodolist" : {
                "type": "array",
                "items" : {
                    "$ref": "#/components/schemas/Todolist"
                }
            }
        }
    }

}